## Урок 1. Алгоритм линейной регрессии. Градиентный спуск

In [1]:
import numpy as np
import matplotlib.pyplot as plt

__Задача:__ предсказание баллов ЕГЭ ученика в зависимости от кол-ва лет стажа его репетитора

In [2]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 5, 3, 0, 5, 10, 1, 2]])
X

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  2,  5,  3,  0,  5, 10,  1,  2]])

In [3]:
X.T

array([[ 1,  1],
       [ 1,  1],
       [ 1,  2],
       [ 1,  5],
       [ 1,  3],
       [ 1,  0],
       [ 1,  5],
       [ 1, 10],
       [ 1,  1],
       [ 1,  2]])

In [4]:
y = [45, 55, 50, 55, 60, 35, 75, 80, 50, 60]

In [5]:
def calc_mae(y, y_pred):
    err = np.mean(np.abs(y - y_pred))
    return err

def calc_mse(y, y_pred):
    err = np.mean((y - y_pred)**2) # <=> 1/n * np.sum((y_pred - y)**2)
    return err

### Д/З

1. Подберите скорость обучения (alpha) и количество итераций

In [6]:
n = X.shape[1]
alpha = 1e-2
W = np.array([1, 0.5])
W_old  = np.array([0,0])
print(f'Number of objects = {n} \
       \nLearning rate = {alpha} \
       \nInitial weights = {W} \n')
i=1
while (W[0]-W_old[0]>alpha) | (W[1]-W_old[1]>alpha):
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    W_old = W.copy()
    for k in range(W.shape[0]):
        W[k] -= alpha * (1/n * 2 * np.sum(X[k] * (y_pred - y)))
    if i % 10 == 0:
        alpha /= 1.1
#         т.к. W содержит уже новые вычисленные значения, а нужно отобразить те,
# которые использовались на данной итерации для подсчета y_pred и err,
# то используем W_old для вывода текущих ("новых") значений
        print(f'Iteration #{i}: W_new = {W_old}, MSE = {round(err,2)}')
    i+=1
print(f'Потребовалось {i-1} итераций')
print(f'Найдены коэффициенты: {W}.')

Number of objects = 10        
Learning rate = 0.01        
Initial weights = [1.  0.5] 

Iteration #10: W_new = [ 6.27409912 10.61491815], MSE = 752.02
Iteration #20: W_new = [ 9.4389504  10.26755155], MSE = 641.65
Iteration #30: W_new = [12.06050824  9.79675466], MSE = 556.94
Iteration #40: W_new = [14.27459742  9.39540476], MSE = 490.42
Iteration #50: W_new = [16.1576422   9.05394988], MSE = 437.48
Iteration #60: W_new = [17.76892015  8.76176985], MSE = 394.83
Iteration #70: W_new = [19.15528901  8.51037327], MSE = 360.09
Iteration #80: W_new = [20.35414242  8.29297969], MSE = 331.51
Iteration #90: W_new = [21.39557972  8.10413109], MSE = 307.78
Iteration #100: W_new = [22.30402559  7.93939844], MSE = 287.92
Iteration #110: W_new = [23.09945118  7.79516027], MSE = 271.16
Iteration #120: W_new = [23.79830356  7.66843417], MSE = 256.93
Iteration #130: W_new = [24.41421909  7.55674738], MSE = 244.78
Iteration #140: W_new = [24.95857578  7.45803669], MSE = 234.33
Iteration #150: W_new =

*2. В этом коде мы избавляемся от итераций по весам, но тут есть ошибка, исправьте ее

In [7]:
n = X.shape[1]
alpha = 1e-2
W = np.array([1, 0.5])
W_pred = np.array([0,0])
print(f'Number of objects = {n} \
       \nLearning rate = {alpha} \
       \nInitial weights = {W} \n')

i=1
while (W[0]-W_pred[0]>alpha) | (W[1]-W_pred[1]>alpha):
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
#     for k in range(W.shape[0]):
#         W[k] -= alpha * (1/n * 2 * np.sum(X[k] * (y_pred - y)))
    W_pred = W.copy()
    W -= [alpha * (1/n * 2 * np.sum(z * (y_pred - y))) for z in X]
    if i % 10 == 0:
        print(f'Iteration #{i}: W_new = {W_pred}, MSE = {round(err,2)}')
        alpha /= 1.1
    i+=1
W

Number of objects = 10        
Learning rate = 0.01        
Initial weights = [1.  0.5] 

Iteration #10: W_new = [ 6.27409912 10.61491815], MSE = 752.02
Iteration #20: W_new = [ 9.4389504  10.26755155], MSE = 641.65
Iteration #30: W_new = [12.06050824  9.79675466], MSE = 556.94
Iteration #40: W_new = [14.27459742  9.39540476], MSE = 490.42
Iteration #50: W_new = [16.1576422   9.05394988], MSE = 437.48
Iteration #60: W_new = [17.76892015  8.76176985], MSE = 394.83
Iteration #70: W_new = [19.15528901  8.51037327], MSE = 360.09
Iteration #80: W_new = [20.35414242  8.29297969], MSE = 331.51
Iteration #90: W_new = [21.39557972  8.10413109], MSE = 307.78
Iteration #100: W_new = [22.30402559  7.93939844], MSE = 287.92
Iteration #110: W_new = [23.09945118  7.79516027], MSE = 271.16
Iteration #120: W_new = [23.79830356  7.66843417], MSE = 256.93
Iteration #130: W_new = [24.41421909  7.55674738], MSE = 244.78
Iteration #140: W_new = [24.95857578  7.45803669], MSE = 234.33
Iteration #150: W_new =

array([29.66920956,  6.60383588])